# Generated by Django 4.2.2 on 2023-06-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_cart_category_products_cartproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
