# Generated by Django 4.2.2 on 2023-06-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_delete_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='slider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
